In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import math
import warnings

## 1. Reading data

In [2]:
data_nba = pd.read_csv("/Users/marcus/Documents/Projects/Final/Final_Project_NBA_Classifier/data/nba_season.txt")
shoot_nba = pd.read_csv("/Users/marcus/Documents/Projects/Final/Final_Project_NBA_Classifier/data/nba_shooting.txt")
test_poss = pd.read_csv("/Users/marcus/Documents/Projects/Final/Final_Project_NBA_Classifier/data/17-18_poss.txt")
test_shoot = pd.read_csv("/Users/marcus/Documents/Projects/Final/Final_Project_NBA_Classifier/data/17-18_shoot.txt")

In [3]:
data_nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Unnamed: 29,ORtg,DRtg
0,1,Steven Adams\adamsst01,C,26,OKC,63,63,1680,8.2,13.8,0.592,0.0,0.1,0.333,8.2,13.7,0.594,3.4,5.8,0.582,6.0,10.9,16.9,4.2,1.5,1.9,2.7,3.5,19.8,NaN,122.0,106
1,2,Bam Adebayo\adebaba01,PF,22,MIA,72,72,2417,8.9,16.0,0.557,0.0,0.3,0.143,8.8,15.7,0.564,5.3,7.7,0.691,3.6,11.3,14.8,7.4,1.7,1.9,4.1,3.7,23.1,NaN,116.0,106
2,3,LaMarcus Aldridge\aldrila01,C,34,SAS,53,53,1754,10.7,21.6,0.493,1.7,4.3,0.389,9.0,17.3,0.519,4.3,5.2,0.827,2.8,7.9,10.7,3.5,1.0,2.4,2.0,3.5,27.3,NaN,115.0,112
3,4,Kyle Alexander\alexaky01,C,23,MIA,2,0,13,3.8,7.5,0.500,0.0,0.0,NaN,3.8,7.5,0.500,0.0,0.0,NaN,7.5,3.8,11.3,0.0,0.0,0.0,3.8,3.8,7.5,NaN,96.0,116
4,5,Nickeil Alexander-Walker\alexani01,SG,21,NOP,47,1,591,7.7,20.8,0.368,3.6,10.4,0.346,4.1,10.4,0.391,2.0,2.9,0.676,0.7,5.9,6.6,7.0,1.3,0.6,4.2,4.5,20.9,NaN,93.0,113

In [4]:
data_nba.shape

(651, 32)

In [5]:
shoot_nba.head()

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,Unnamed: 9,2P,0-3,3-10,10-16,16-3P,3P,Unnamed: 16,2P.1,0-3.1,3-10.1,10-16.1,16-3P.1,3P.1,Unnamed: 23,2P.2,3P.2,Unnamed: 26,%FGA,#,Unnamed: 29,%3PA,3P%,Unnamed: 32,Att.,#.1
0,1,Steven Adams\adamsst01,C,26,OKC,63,1680,0.592,4.4,NaN,0.994,0.513,0.397,0.082,0.002,0.006,NaN,0.594,0.743,0.416,0.513,1.000,0.333,NaN,0.670,1.000,NaN,0.176,78,NaN,0.333,0.000,NaN,1,1
1,2,Bam Adebayo\adebaba01,PF,22,MIA,72,2417,0.557,5.8,NaN,0.982,0.481,0.301,0.144,0.056,0.018,NaN,0.564,0.726,0.445,0.404,0.227,0.143,NaN,0.715,0.500,NaN,0.219,157,NaN,0.571,0.125,NaN,1,0
2,3,LaMarcus Aldridge\aldrila01,C,34,SAS,53,1754,0.493,13.7,NaN,0.802,0.202,0.129,0.227,0.245,0.198,NaN,0.519,0.719,0.471,0.461,0.433,0.389,NaN,0.567,0.951,NaN,0.044,31,NaN,0.185,0.379,NaN,1,0
3,4,Kyle Alexander\alexaky01,C,23,MIA,2,13,0.500,1.5,NaN,1.000,1.000,0.000,0.000,0.000,0.000,NaN,0.500,0.500,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.000,0,NaN,NaN,NaN,NaN,0,0
4,5,Nickeil Alexander-Walker\alexani01,SG,21,NOP,47,591,0.368,15.9,NaN,0.500,0.244,0.173,0.053,0.030,0.500,NaN,0.391,0.523,0.261,0.214,0.375,0.346,NaN,0.192,0.913,NaN,0.008,2,NaN,0.188,0.360,NaN,4,0

In [6]:
shoot_nba.shape

(651, 35)

## 2. Dropping columns

In [7]:
data_nba.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Unnamed: 29',
       'ORtg', 'DRtg'],
      dtype='object')

Looking at the dataset of stats per 100 Possesions we can drop the following:
- Ranking, Age, Unnamed: 29, Games started
- Shooting Percentages since we also have columns for attempted and made shots for each category

In [8]:
data_nba = data_nba.drop(columns=["Rk","Age", "Unnamed: 29", "GS","FG%","3P%","2P%", "FT%"])
test_poss = test_poss.drop(columns=["Rk","Age", "Unnamed: 29", "GS","FG%","3P%","2P%", "FT%"])

In [9]:
shoot_nba.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'FG%', 'Dist.',
       'Unnamed: 9', '2P', '0-3', '3-10', '10-16', '16-3P', '3P',
       'Unnamed: 16', '2P.1', '0-3.1', '3-10.1', '10-16.1', '16-3P.1', '3P.1',
       'Unnamed: 23', '2P.2', '3P.2', 'Unnamed: 26', '%FGA', '#',
       'Unnamed: 29', '%3PA', '3P%', 'Unnamed: 32', 'Att.', '#.1'],
      dtype='object')

Looking at the dataset of shots we can drop the following:
- Ranking, Age, Team, #
- Position, Games and Minutes played since they are already included in the other table

In [10]:
shoot_nba = shoot_nba.drop(columns=["Age","Tm","#","Rk","Pos","G","MP","Unnamed: 9",
                                    "Unnamed: 16","Unnamed: 23", "Unnamed: 29", "Unnamed: 32",
                                    "Unnamed: 26","Att.","#.1"])
test_shoot = test_shoot.drop(columns=["Age","Tm","#","Rk","Pos","G","MP","Unnamed: 9",
                                    "Unnamed: 16","Unnamed: 23", "Unnamed: 29", "Unnamed: 32",
                                    "Unnamed: 26","Att.","#.1"])

## 3. Cleaning/Conatenating dataset/tables

For the shoot dataset we need to rename the columns since the initial table from basketball-reference had subheaders.

In [11]:
shoot_nba = shoot_nba.rename(columns={"Dist.": "avg_shoot_dist", '2P': "2P_FGA", '0-3': "2P_0-3", '3-10': "2P_3-10",
 '10-16': "2P_10-16", '16-3P': "2P_16-3P", '3P': "3P_FGA", '2P.1': "2P%", '0-3.1': "2P%_0-3",
 '3-10.1': "2P%_3-10", '10-16.1': "2P%_10-16", '16-3P.1': "2P%_16-3P", '3P.1': "3P%", '2P.2': "2P%_asst",
 '3P.2': "3P%_asst", '%FGA': "Dunks%_FGA", '%3PA': "Corner3%_3PA", '3P%': "Corner3%"})
test_shoot = test_shoot.rename(columns={"Dist.": "avg_shoot_dist", '2P': "2P_FGA", '0-3': "2P_0-3", '3-10': "2P_3-10",
 '10-16': "2P_10-16", '16-3P': "2P_16-3P", '3P': "3P_FGA", '2P.1': "2P%", '0-3.1': "2P%_0-3",
 '3-10.1': "2P%_3-10", '10-16.1': "2P%_10-16", '16-3P.1': "2P%_16-3P", '3P.1': "3P%", '2P.2': "2P%_asst",
 '3P.2': "3P%_asst", '%FGA': "Dunks%_FGA", '%3PA': "Corner3%_3PA", '3P%': "Corner3%"})

In [12]:
shoot_nba.shape

(651, 20)

In [13]:
data_nba.shape

(651, 24)

Concatenating both tables based on the player.

In [14]:
complete_nba = pd.concat([data_nba.set_index('Player'),shoot_nba.set_index('Player')], axis=1, join='inner').reset_index()
test_nba = pd.concat([test_poss.set_index('Player'),test_shoot.set_index('Player')], axis=1, join='inner').reset_index()

In [15]:
complete_nba.head()

,Player,Pos,Tm,G,MP,FG,FGA,3P,3PA,2P,2PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,FG%,avg_shoot_dist,2P_FGA,2P_0-3,2P_3-10,2P_10-16,2P_16-3P,3P_FGA,2P%,2P%_0-3,2P%_3-10,2P%_10-16,2P%_16-3P,3P%,2P%_asst,3P%_asst,Dunks%_FGA,Corner3%_3PA,Corner3%
0,Steven Adams\adamsst01,C,OKC,63,1680,8.2,13.8,0.0,0.1,8.2,13.7,3.4,5.8,6.0,10.9,16.9,4.2,1.5,1.9,2.7,3.5,19.8,122.0,106,0.592,4.4,0.994,0.513,0.397,0.082,0.002,0.006,0.594,0.743,0.416,0.513,1.000,0.333,0.670,1.000,0.176,0.333,0.000
1,Bam Adebayo\adebaba01,PF,MIA,72,2417,8.9,16.0,0.0,0.3,8.8,15.7,5.3,7.7,3.6,11.3,14.8,7.4,1.7,1.9,4.1,3.7,23.1,116.0,106,0.557,5.8,0.982,0.481,0.301,0.144,0.056,0.018,0.564,0.726,0.445,0.404,0.227,0.143,0.715,0.500,0.219,0.571,0.125
2,LaMarcus Aldridge\aldrila01,C,SAS,53,1754,10.7,21.6,1.7,4.3,9.0,17.3,4.3,5.2,2.8,7.9,10.7,3.5,1.0,2.4,2.0,3.5,27.3,115.0,112,0.493,13.7,0.802,0.202,0.129,0.227,0.245,0.198,0.519,0.719,0.471,0.461,0.433,0.389,0.567,0.951,0.044,0.185,0.379
3,Kyle Alexander\alexaky01,C,MIA,2,13,3.8,7.5,0.0,0.0,3.8,7.5,0.0,0.0,7.5,3.8,11.3,0.0,0.0,0.0,3.8,3.8,7.5,96.0,116,0.500,1.5,1.000,1.000,0.000,0.000,0.000,0.000,0.500,0.500,NaN,NaN,NaN,NaN,0.000,NaN,0.000,NaN,NaN
4,Nickeil Alexander-Walker\alexani01,SG,NOP,47,591,7.7,20.8,3.6,10.4,4.1,10.4,2.0,2.9,0.7,5.9,6.6,7.0,1.3,0.6,4.2,4.5,20.9,93.0,113,0.368,15.9,0.500,0.244,0.173,0.053,0.030,0.500,0.391,0.523,0.261,0.214,0.375,0.346,0.192,0.913,0.008,0.188,0.360

In the database of basketball-reference some players have associated 2 Positions. Since we just want to predict 5 Positions I decided to use only the first mentioned position and assign it to the player.

In [16]:
complete_nba.Pos.value_counts()

SG       143
PF       138
C        134
SF       111
PG       106
PF-C       5
SF-PF      3
PF-SF      3
SG-PG      2
SF-SG      2
SG-SF      1
PG-SG      1
SF-C       1
C-PF       1
Name: Pos, dtype: int64

In [17]:
complete_nba['Pos'] = complete_nba['Pos'].map(lambda x: x.split('-')[0])
test_nba['Pos'] = test_nba['Pos'].map(lambda x: x.split('-')[0])

In the database we have Minutes played (MP) as an absolute number In order to have a comparable value across all players I will calculate the Minutes played per Game as a new column and drop the absolute value.

In [18]:
complete_nba["MPG"] = complete_nba["MP"]/complete_nba["G"]
test_nba["MPG"] = test_nba["MP"]/test_nba["G"]

In [19]:
complete_nba = complete_nba.drop(columns=["MP"])
test_nba = test_nba.drop(columns=["MP"])

## 4. Filtering out data

A game in the nba takes 48 minutes and 5 players are on the court at the same time. For the purpose of this model I want to make sure that I only take into account rotational players who play enough minutes per game. For this I have decided to use only players who have played more than 9 Minutes per Game. In addition a player should have played mor than 10 games in the whole season of 82 games.

In [20]:
complete_nba.shape

(651, 43)

In [21]:
len(complete_nba.loc[(complete_nba['MPG'] >= 10) & (complete_nba['G'] > 10)])

481

In [22]:
clean_nba = complete_nba.loc[(complete_nba['MPG'] >= 10) & (complete_nba['G'] > 10)]
test_clean_nba = test_nba.loc[(test_nba['MPG'] >= 10) & (test_nba['G'] > 10)]

## 5. Final Cleaning

Cecking for nulls and replacing them with 0 since they are related to players who havent shoot from a certain distance.

In [23]:
clean_nba.isna().sum()

Player             0
Pos                0
Tm                 0
G                  0
FG                 0
FGA                0
3P                 0
3PA                0
2P                 0
2PA                0
FT                 0
FTA                0
ORB                0
DRB                0
TRB                0
AST                0
STL                0
BLK                0
TOV                0
PF                 0
PTS                0
ORtg               0
DRtg               0
FG%                0
avg_shoot_dist     0
2P_FGA             0
2P_0-3             0
2P_3-10            0
2P_10-16           0
2P_16-3P           0
3P_FGA             0
2P%                0
2P%_0-3            0
2P%_3-10           1
2P%_10-16         12
2P%_16-3P         25
3P%               12
2P%_asst           0
3P%_asst          27
Dunks%_FGA         0
Corner3%_3PA      12
Corner3%          22
MPG                0
dtype: int64

In [24]:
def nans(df): return df[df.isnull().any(axis=1)]

nulls_clean_nba = nans(clean_nba)

In [25]:
nulls_clean_nba.head()

,Player,Pos,Tm,G,FG,FGA,3P,3PA,2P,2PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,FG%,avg_shoot_dist,2P_FGA,2P_0-3,2P_3-10,2P_10-16,2P_16-3P,3P_FGA,2P%,2P%_0-3,2P%_3-10,2P%_10-16,2P%_16-3P,3P%,2P%_asst,3P%_asst,Dunks%_FGA,Corner3%_3PA,Corner3%,MPG
6,Jarrett Allen\allenja01,C,BRK,70,7.7,11.9,0.0,0.2,7.7,11.7,4.4,6.9,5.5,11.6,17.1,2.8,1.0,2.4,2.0,4.1,19.8,132.0,106,0.649,2.6,0.987,0.755,0.211,0.019,0.002,0.013,0.658,0.746,0.367,0.444,0.000,0.000,0.795,NaN,0.447,0.833,0.000,26.457143
8,Al-Farouq Aminu\aminual01,PF,ORL,18,3.2,11.0,1.2,4.6,2.0,6.4,2.4,3.7,3.1,8.1,11.1,2.7,2.3,1.0,2.2,3.5,10.0,88.0,108,0.291,13.3,0.581,0.267,0.244,0.000,0.070,0.419,0.320,0.435,0.190,NaN,0.333,0.250,0.438,0.889,0.012,0.222,0.375,21.111111
49,Dragan Bender\bendedr01,PF,TOT,16,6.8,15.2,2.5,7.1,4.3,8.1,1.6,2.3,2.6,9.4,12.0,4.6,0.7,1.5,3.5,6.9,17.6,102.0,110,0.446,13.9,0.533,0.272,0.261,0.000,0.000,0.467,0.531,0.680,0.375,NaN,NaN,0.349,0.846,1.000,0.065,0.279,0.417,17.875000
54,Khem Birch\birchkh01,C,ORL,48,3.9,7.6,0.0,0.1,3.9,7.5,3.5,5.3,4.8,6.8,11.6,2.6,1.1,1.2,1.6,4.8,11.2,121.0,111,0.510,4.5,0.993,0.476,0.448,0.063,0.007,0.007,0.514,0.706,0.344,0.222,1.000,0.000,0.671,NaN,0.175,1.000,0.000,19.208333
56,Bismack Biyombo\biyombi01,C,CHO,53,7.4,13.5,0.0,0.0,7.4,13.5,4.4,7.4,5.8,9.2,15.0,2.4,0.5,2.4,2.3,5.6,19.1,116.0,112,0.543,3.6,1.000,0.604,0.320,0.065,0.011,0.000,0.543,0.702,0.315,0.278,0.000,NaN,0.834,NaN,0.212,NaN,NaN,19.415094

In [26]:
clean_nba = clean_nba.fillna(0)
test_clean_nba = test_clean_nba.fillna(0)

Clean player names from the addition after the the backslash and organize the order of columns.

In [27]:
clean_nba['player_new'] = clean_nba['Player'].str.split('\\').str[0]
test_clean_nba['player_new'] = test_clean_nba['Player'].str.split('\\').str[0]

In [28]:
clean_nba = clean_nba.drop(columns=["Player"])
test_clean_nba = test_clean_nba.drop(columns=["Player"])

In [29]:
clean_nba = clean_nba[['player_new','Pos','Tm', 'G', 'MPG', 'FG', 'FGA', '3P', '3PA', '2P', '2PA', '2P%','2P%', 'FT', 'FTA',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'ORtg',
       'DRtg', 'FG%', 'avg_shoot_dist', '2P_FGA', '2P_0-3', '2P_3-10',
       '2P_10-16', '2P_16-3P', '3P_FGA', '2P%_0-3', '2P%_3-10',
       '2P%_10-16', '2P%_16-3P', '3P%', '2P%_asst', '3P%_asst', 'Dunks%_FGA',
       'Corner3%_3PA', 'Corner3%']]
test_clean_nba = test_clean_nba[['player_new','Pos','Tm', 'G', 'MPG', 'FG', 'FGA', '3P', '3PA', '2P', '2PA', '2P%','2P%', 'FT', 'FTA',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'ORtg',
       'DRtg', 'FG%', 'avg_shoot_dist', '2P_FGA', '2P_0-3', '2P_3-10',
       '2P_10-16', '2P_16-3P', '3P_FGA', '2P%_0-3', '2P%_3-10',
       '2P%_10-16', '2P%_16-3P', '3P%', '2P%_asst', '3P%_asst', 'Dunks%_FGA',
       'Corner3%_3PA', 'Corner3%']]

In [30]:
clean_nba = clean_nba.loc[:,~clean_nba.columns.duplicated()]
test_clean_nba = test_clean_nba.loc[:,~test_clean_nba.columns.duplicated()]

In [31]:
clean_nba.head()

,player_new,Pos,Tm,G,MPG,FG,FGA,3P,3PA,2P,2PA,2P%,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,FG%,avg_shoot_dist,2P_FGA,2P_0-3,2P_3-10,2P_10-16,2P_16-3P,3P_FGA,2P%_0-3,2P%_3-10,2P%_10-16,2P%_16-3P,3P%,2P%_asst,3P%_asst,Dunks%_FGA,Corner3%_3PA,Corner3%
0,Steven Adams,C,OKC,63,26.666667,8.2,13.8,0.0,0.1,8.2,13.7,0.594,3.4,5.8,6.0,10.9,16.9,4.2,1.5,1.9,2.7,3.5,19.8,122.0,106,0.592,4.4,0.994,0.513,0.397,0.082,0.002,0.006,0.743,0.416,0.513,1.000,0.333,0.670,1.000,0.176,0.333,0.000
1,Bam Adebayo,PF,MIA,72,33.569444,8.9,16.0,0.0,0.3,8.8,15.7,0.564,5.3,7.7,3.6,11.3,14.8,7.4,1.7,1.9,4.1,3.7,23.1,116.0,106,0.557,5.8,0.982,0.481,0.301,0.144,0.056,0.018,0.726,0.445,0.404,0.227,0.143,0.715,0.500,0.219,0.571,0.125
2,LaMarcus Aldridge,C,SAS,53,33.094340,10.7,21.6,1.7,4.3,9.0,17.3,0.519,4.3,5.2,2.8,7.9,10.7,3.5,1.0,2.4,2.0,3.5,27.3,115.0,112,0.493,13.7,0.802,0.202,0.129,0.227,0.245,0.198,0.719,0.471,0.461,0.433,0.389,0.567,0.951,0.044,0.185,0.379
4,Nickeil Alexander-Walker,SG,NOP,47,12.574468,7.7,20.8,3.6,10.4,4.1,10.4,0.391,2.0,2.9,0.7,5.9,6.6,7.0,1.3,0.6,4.2,4.5,20.9,93.0,113,0.368,15.9,0.500,0.244,0.173,0.053,0.030,0.500,0.523,0.261,0.214,0.375,0.346,0.192,0.913,0.008,0.188,0.360
5,Grayson Allen,SG,MEM,38,18.894737,7.6,16.3,3.7,9.2,3.9,7.2,0.545,2.5,2.9,0.5,5.0,5.5,3.4,0.7,0.1,2.1,3.4,21.5,114.0,115,0.466,16.9,0.438,0.151,0.179,0.104,0.004,0.562,0.711,0.444,0.500,0.000,0.404,0.600,0.982,0.044,0.255,0.556

Drop column Games since we only needed it for the calculation of Minutes per Gam and to filter out the players who werent really active in that season.

In [32]:
clean_nba = clean_nba.drop(columns=["G"])
test_clean_nba = test_clean_nba.drop(columns=["G"])

In [33]:
clean_nba.to_csv(r'/Users/marcus/Documents/Projects/Final/Final_Project_NBA_Classifier/data/clean_nba.csv', index = False)

test_clean_nba.to_csv(r'/Users/marcus/Documents/Projects/Final/Final_Project_NBA_Classifier/data/test_clean_nba.csv', index = False)